config/routes.rb
Rails.application.routes.draw do

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :teams

  resources :cards

  root 'cards#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
  validates :name, :remaining_hour, :own_player, presence: true
  validates :remaining_hour, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 720}

  belongs_to :team

  def calc_remaining_hour_from_now
    # 更新時と残り時間から、現在からの残り時間を算出する（結果は四捨五入）
    {:updated_at => updated_at, :remaining_hour => remaining_hour}
    (((updated_at + remaining_hour * 60 * 60) - Time.now) / 60 / 60).round
  end

  def display_style
    if self.calc_remaining_hour_from_now <= 0
      "background-color: #9e9e9e;"
    elsif self.calc_remaining_hour_from_now <= 24
      "background-color: #ff7d7d;"
    end
  end

  def display_remaining_hour
    if self.calc_remaining_hour_from_now <= 0
      "期限切れ"
    else
      self.calc_remaining_hour_from_now.to_s + " 時間"
    end
  end

  def self.sort_by_remaining_hour(cards)
    @cards = cards.sort { |x, y| x.calc_remaining_hour_from_now <=> y.calc_remaining_hour_from_now }
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true, length: {maximum: 40}
  has_secure_password

  has_many :card, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authorize

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def authorize
    unless Team.find_by_id(session[:team_id])
      redirect_to login_url, alert: "ログインしてください"
    end
  end

  def current_team
    Team.find_by_id(session[:team_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to login_url, alert: "セッション情報の取得に失敗しました、再度ログインしてください。"
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.where(team_id: session[:team_id])
    @cards = Card.sort_by_remaining_hour(@cards)
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    @card.team_id = session[:team_id]

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: "#{@card.name} を登録しました" }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: "#{@card.name}のカード情報を更新しました" }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: "#{@card.own_player} の #{@card.name} を削除しました" }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_card
    @card = Card.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def card_params
    params.require(:card).permit(:name, :remaining_hour, :own_player)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize, only: [:new, :create]

  def new
  end

  def create
    team = Team.find_by_name(params[:name])
    if team and team.authenticate(params[:password])
      session[:team_id] = team.id
      redirect_to cards_url
    else
      redirect_to login_url, alert: "無効なチーム名 / パスワードの組み合わせです"
    end
  end

  def destroy
    session[:team_id] = nil
    redirect_to login_url, alert: "ログアウトしました"
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authorize, only: [:new, :create]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.order(:name)
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to teams_url, notice: "#{@team.name} を登録しました" }
        format.json { render :show, status: :created, location: @team }
        session[:team_id] = @team.id
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to teams_url, notice: "#{@team.name} を更新しました" }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: "#{@team.name} を削除しました" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "カード名" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :remaining_hour, "残り時間[h]" %><br />
    <%= f.number_field :remaining_hour %>
  </div>
  <div class="field">
    <%= f.label :own_player, "所有者" %><br />
    <%= f.text_field :own_player %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<div class="app_form">
  <fieldset>
    <legend>カードの編集を入力してください</legend>
    <%= render 'form' %>
  </fieldset>
</div>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<h1>カード一覧</h1>

<table>
  <thead>
  <tr>
    <th>カード名</th>
    <th>残り時間</th>
    <th>所有者</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @cards.each do |card| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>" style="<%= card.display_style %>">
        <td><%= card.name %></td>
        <td><%= card.display_remaining_hour %></td>
        <td><%= card.own_player %></td>
        <td class="list_actions"><%= link_to 'Show', card %></td>
        <td class="list_actions"><%= link_to 'Edit', edit_card_path(card) %></td>
        <td class="list_actions"><%= link_to 'Destroy', card, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<div class="app_form">
  <fieldset>
    <legend>カードの情報を入力してください</legend>
    <%= render 'form' %>
  </fieldset>
</div>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<p>
  <strong>カード名:</strong>
  <%= @card.name %>
</p>

<p>
  <strong>残り時間(登録時点)[h]:</strong>
  <%= @card.remaining_hour %>
</p>

<p>
  <strong>所有者:</strong>
  <%= @card.own_player %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DqCardManager</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Varela' rel='stylesheet' type='text/css'>
</head>
<body class='<%= controller.controller_name %>'>
<div id="banner">
  <%= @page_title || "DQ Card Manager" %>
</div>
<div id="columns">
  <div id="main">
    <% if Team.find_by_id(session[:team_id]) %>
      <div><%= Team.find_by_id(session[:team_id]).name %> でログイン中</div>
    <% end %>

    <%= yield %>
  </div>
</div>

<% if session[:team_id] %>
  <%= button_to 'ログアウト', logout_path, method: :delete %>
<% end %>

<footer>
  <div>&copy; 2014 chan_gami</div>
</footer>
</body>
</html>